{% set name = "python-jsonrpc-server" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccc221b82e37853ed3fd3b64ca30b0562348127598b32413f70936fde82261d9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - ujson

test:
  imports:
    - pyls_jsonrpc
    - pyls_jsonrpc.dispatchers

about:
  home: https://github.com/palantir/python-jsonrpc-server
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'A Python 2.7 and 3.4+ server implementation of the JSON RPC 2.0 protocol.'
  dev_url: https://github.com/palantir/python-jsonrpc-server

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
