{% set name = "python-jsonrpc-server" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 533434fa982eb42c36ddb0b6758cef8e6eaf46d014f76b70a401b8790a3e6d57

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future

test:
  imports:
    - jsonrpc
    - jsonrpc.dispatchers

about:
  home: https://github.com/palantir/python-jsonrpc-server
  license: MIT
  license_family: MIT
  summary: 'A Python 2.7 and 3.4+ server implementation of the JSON RPC 2.0 protocol.'
  dev_url: https://github.com/palantir/python-jsonrpc-server

extra:
  recipe-maintainers:
    - ccordoba12
    - andfoy
