travis:
  secure:
    BINSTAR_TOKEN: nor3ADHSoihaoPE8Dlb8JBPChwIfL7qJH1HB++q5byGg8IBhxfjg3Fqfzl4N6IOBvnGV9L9NGdoBeiAYxFb7Tw67PqEEVZ9h47VyMUCmo+vVMFplER714jNePPwprChGP5GkyybCSSnuAfWflyCA4lQbLE7YYPTeYgqnPIc3+VYRwoHocxUH41XT2RTA5k0hsZYKPGPcqGcUwdezrUZJVwrSmTfT4dM/cO931CYirWfMi/oxYHGNlev1YKgAgPOt0vffGgIHVFoejsxKmcQfDwqXMk2DpZgKIKbz/JAKrPGAPwEyRhNMU6xUqlW4N5wqNhbgpmxf0CF20d2SLgzRJ6E2C6fgvSSZWxMysFrFa210O10a05/xj4paAQ7XRybUM8+4EpPhb3bgwJsB6Pw68t3cuJ3gX0nCHRNSB495HxfnLRwVEtyVYq/UWLxbw6Z9c+Eyjc5pNas95pWDH0VtGfotAIzlKcaUUWjknhoJmCVMiVnetEaBSex/8NuikNoNgRnUQA4VYiE9D4NyBdgiWQm7YIt4s8BAPd6JK3oIwX7q4OciQTRtaR2sUlPVM3mdHdzPhp28iaAh/A1WNn7cQiA9SohKyhk3WFY3ImprOV2qRxmnfvXRtUL7WlZx9pPB4/17U09dfaeCWiHcFTm1nDzp1L3A2Yak3y8SW/J+EkM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
